version: "2.1"
services:

  #
  # jobmanager and taskmanager based on session cluster
  # https://ci.apache.org/projects/flink/flink-docs-release-1.9/ops/deployment/docker.html#flink-session-cluster
  #
  jobmanager:
    image: flink:${FLINK_VERSION}
    expose:
      - "6123"
    ports:
      - "8081:8081"
    command: jobmanager
    environment:
      - JOB_MANAGER_RPC_ADDRESS=localhost
    network_mode: host

  taskmanager:
    image: flink:${FLINK_VERSION}
    expose:
      - "6121"
      - "6122"
    depends_on:
      - jobmanager
    command: taskmanager
    environment:
      - JOB_MANAGER_RPC_ADDRESS=localhost
      - GOOGLE_APPLICATION_CREDENTIALS=${GOOGLE_APPLICATION_CREDENTIALS}
    volumes:
      - ./gcs-key.json:${GOOGLE_APPLICATION_CREDENTIALS}
    network_mode: host

  jobserver:
    image: ${GCR_HOSTNAME}/${PROJECT_ID}/flink-job-server:${BEAM_RELEASE}
    command: [ "--artifacts-dir", "${ARTIFACTS_DIR}", "--flink-master-url",
               "${FLINK_MASTER_URL}", "--job-host", "${JOB_HOST}", "--job-port", "${JOB_PORT}",
               "--clean-artifacts-per-job", "true" ]
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=${GOOGLE_APPLICATION_CREDENTIALS}
    volumes:
      - ./gcs-key.json:${GOOGLE_APPLICATION_CREDENTIALS}
    network_mode: host

  python-sdk:
    image: ${GCR_HOSTNAME}/${PROJECT_ID}/python3.7_sdk:${BEAM_RELEASE}
    expose:
      - "50000"
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=${GOOGLE_APPLICATION_CREDENTIALS}
    volumes:
      - ./gcs-key.json:${GOOGLE_APPLICATION_CREDENTIALS}
    command: --worker_pool
    network_mode: host

  beam:
    build: ./samples
    image: beam:latest
    environment:
      - PROJECT_ID=${PROJECT_ID}
      - SDK_ENDPOINT=localhost:50000
      - JOB_SERVER=localhost:8099
    network_mode: host

  #
  # FOR DEVELOPMENT PURPOSE
  # Zookeeper configurtion
  # Based on
  # https://hub.docker.com/_/zookeeper
  #
  zoo:
    image: zookeeper
    network_mode: host
    environment:
      - ZOO_STANDALONE_ENABLED=true

  #
  # FOR DEVELOPMENT PURPOSE
  # Kafka configuration for single node cluster
  # Based on
  # https://docs.confluent.io/current/installation/docker/config-reference.html#confluent-kafka-configuration
  #
  kafka:
    image: confluentinc/cp-kafka
    network_mode: host
    environment:
      - KAFKA_ZOOKEEPER_CONNECT=localhost:2181
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
      - KAFKA_LISTENERS=PLAINTEXT://localhost:9092
      - KAFKA_BROKER_ID=1
      - KAFKA_CONFLUENT_SUPPORT_METRICS.ENABLE=false
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
    depends_on:
      - zoo
