version: "2.1"
services:

  #
  # jobmanager and taskmanager based on session cluster
  # https://ci.apache.org/projects/flink/flink-docs-release-1.9/ops/deployment/docker.html#flink-session-cluster
  #
  jobmanager:
    image: flink:${FLINK_VERSION}
    expose:
      - "6123"
    ports:
      - "8081:8081"
    command: jobmanager
    environment:
      - JOB_MANAGER_RPC_ADDRESS=jobmanager
    networks:
      - pipeline

  taskmanager:
    image: flink:${FLINK_VERSION}
    expose:
      - "6121"
      - "6122"
    depends_on:
      - jobmanager
    command: taskmanager
    environment:
      - JOB_MANAGER_RPC_ADDRESS=jobmanager
      - GOOGLE_APPLICATION_CREDENTIALS=${GOOGLE_APPLICATION_CREDENTIALS}
    volumes:
      - ./gcs-key.json:${GOOGLE_APPLICATION_CREDENTIALS}
    networks:
      - pipeline

  jobserver:
    image: ${GCR_HOSTNAME}/${PROJECT_ID}/flink-job-server:${BEAM_RELEASE}
    command: [ "--artifacts-dir", "${ARTIFACTS_DIR}", "--flink-master-url",
               "${FLINK_MASTER_URL}", "--job-host", "${JOB_HOST}", "--job-port", "${JOB_PORT}",
               "--clean-artifacts-per-job", "true" ]
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=${GOOGLE_APPLICATION_CREDENTIALS}
    volumes:
      - ./gcs-key.json:${GOOGLE_APPLICATION_CREDENTIALS}
    networks:
      - pipeline

  python-sdk:
    image: ${GCR_HOSTNAME}/${PROJECT_ID}/python3.7_sdk:${BEAM_RELEASE}
    expose:
      - "50000"
    command: --worker_pool
    networks:
      - pipeline

  beam:
    build: ./samples
    image: beam:latest
    environment:
      - SDK_ENDPOINT=python-sdk:50000
      - JOB_SERVER=jobserver:8099
    networks:
      - pipeline
    
networks:
  pipeline:
